# Generated by Django 2.2.10 on 2020-04-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191105_0426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name_plural': 'BillingAddresses'},
        ),
    ]
